server:
  port: 8082
  tomcat:
    threads:
      max: 25
    accept-count: 25
    max-connections: 100
feign:
  sentinel:
    enabled: true # 开启feign对sentinel的支持
spring:
  application:
    name: cart-service # 服务名称
  profiles:
    active: local
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.100.130:8090
      http-method-specify: true
hm:
  db:
    database: hm-cart
  swagger:
    title: "黑马商城购物车服务接口文档"
    package: com.hmall.cart.controller
